/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesrpl;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author cups
 */
public class MainProgram extends javax.swing.JFrame {

    private PanelLogin pLogin;
    private PanelViewData pView;
    private PanelPegawai pPegawai;
    private PanelPenjualan pPpenjualan;
    private PanelBarang pBarang;
    private PanelChangeBio pChangeBio;
    private PanelChangePass pChangePass;
    private PanelSales pSales;
    private PanelHome pHome;
    private PanelGudang pGudang;
    private PanelPermintaan pPermintaan;
    private PanelPengajuan pPengajuan;
    private final Koneksi conn = new Koneksi();
    private Pegawai pg;
    private Encryption e;

    /**
     * Creates new form MainProgram
     */
    /**
     * Creates new form MainProgram
     */
    public MainProgram() {
        initComponents();
        
        showPanel("pHome");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void showPanel(String panelIdentifier) {
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, panelIdentifier);
    }

    public void setMenu() {
        pPegawai = new PanelPegawai(pg);
        pView = new PanelViewData(pg);
        pPpenjualan = new PanelPenjualan(pg);
        pLogin = new PanelLogin();
        pChangeBio = new PanelChangeBio(pg);
        pChangePass = new PanelChangePass(pg);
        pBarang = new PanelBarang();
        pSales = new PanelSales();
        pHome = new PanelHome();
        pGudang = new PanelGudang();
        pPermintaan = new PanelPermintaan(pg);
        pPengajuan = new PanelPengajuan(pg);

        mainPanel.add("pPegawai", pPegawai);
        mainPanel.add("pView", pView);
        mainPanel.add("pPenjualan", pPpenjualan);
        mainPanel.add("pLogin", pLogin);
        mainPanel.add("pChangeBio", pChangeBio);
        mainPanel.add("pChangePass", pChangePass);
        mainPanel.add("pBarang", pBarang);
        mainPanel.add("pSales", pSales);
        mainPanel.add("pHome", pHome);
        mainPanel.add("pGudang", pGudang);
        mainPanel.add("pPermintaan", pPermintaan);
        mainPanel.add("pPengajuan", pPengajuan);
    }

    public void enableMenu() {
        menuBarang.setEnabled(true);
        menuPegawai.setEnabled(true);
        menuPenjualan.setEnabled(true);
        menuSales.setEnabled(true);
        menuSetPass.setEnabled(true);
        menuSetProfil.setEnabled(true);
        menuView.setEnabled(true);
        menuPengajuan.setEnabled(true);
        menuPermintaan.setEnabled(true);
        menuGudang.setEnabled(true);
    }

    public void setUser(Pegawai pg) {
        this.pg = pg;
        lbluser.setText(pg.getNama());
        enableMenu();
        setMenu();
        showPanel("pHome");
        if(pg.getPosisi().equals("admin")){
            
        }else if(pg.getPosisi().equals("Manager")){
            
        }else if(pg.getPosisi().equals("Sales")){
        
        }else{
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuBar1 = new javax.swing.JMenu();
        menuView = new javax.swing.JMenuItem();
        menuPegawai = new javax.swing.JMenuItem();
        menuBarang = new javax.swing.JMenuItem();
        menuPenjualan = new javax.swing.JMenuItem();
        menuGudang = new javax.swing.JMenuItem();
        menuPengajuan = new javax.swing.JMenuItem();
        menuSales = new javax.swing.JMenuItem();
        menuPermintaan = new javax.swing.JMenuItem();
        menuBar2 = new javax.swing.JMenu();
        menuSetProfil = new javax.swing.JMenuItem();
        menuSetPass = new javax.swing.JMenuItem();
        menuLog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setVerifyInputWhenFocusTarget(false);
        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Selamat datang, ");

        lbluser.setText("user");

        menuBar1.setText("Menu");
        menuBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBar1ActionPerformed(evt);
            }
        });

        menuView.setText("Lihat Data");
        menuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuViewActionPerformed(evt);
            }
        });
        menuBar1.add(menuView);

        menuPegawai.setText("Form Pegawai");
        menuPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPegawaiActionPerformed(evt);
            }
        });
        menuBar1.add(menuPegawai);

        menuBarang.setText("Form Barang");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        menuBar1.add(menuBarang);

        menuPenjualan.setText("Form Penjualan");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        menuBar1.add(menuPenjualan);

        menuGudang.setText("Form Gudang");
        menuGudang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGudangActionPerformed(evt);
            }
        });
        menuBar1.add(menuGudang);

        menuPengajuan.setText("Form Pengajuan");
        menuPengajuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPengajuanActionPerformed(evt);
            }
        });
        menuBar1.add(menuPengajuan);

        menuSales.setText("Data Penjualan Sales");
        menuSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalesActionPerformed(evt);
            }
        });
        menuBar1.add(menuSales);

        menuPermintaan.setText("Data Permintaan Barang");
        menuPermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPermintaanActionPerformed(evt);
            }
        });
        menuBar1.add(menuPermintaan);

        menuBar.add(menuBar1);

        menuBar2.setText("Account");

        menuSetProfil.setText("Ubah Profil");
        menuSetProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSetProfilActionPerformed(evt);
            }
        });
        menuBar2.add(menuSetProfil);

        menuSetPass.setText("Ubah Password");
        menuSetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSetPassActionPerformed(evt);
            }
        });
        menuBar2.add(menuSetPass);

        menuLog.setText("Logout");
        menuLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogActionPerformed(evt);
            }
        });
        menuBar2.add(menuLog);

        menuBar.add(menuBar2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbluser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(445, 445, 445))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_menuLogActionPerformed

    private void menuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPegawaiActionPerformed
        // TODO add your handling code here:
        showPanel("pPegawai");
    }//GEN-LAST:event_menuPegawaiActionPerformed

    private void menuViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViewActionPerformed
        // TODO add your handling code here:
        showPanel("pView");
    }//GEN-LAST:event_menuViewActionPerformed

    private void menuBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBar1ActionPerformed

    private void menuSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalesActionPerformed
        // TODO add your handling code here:
        showPanel("pSales");
    }//GEN-LAST:event_menuSalesActionPerformed

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        // TODO add your handling code here:
        showPanel("pBarang");
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        // TODO add your handling code here:
        showPanel("pPenjualan");
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void menuSetProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSetProfilActionPerformed
        // TODO add your handling code here:
        showPanel("pChangeBio");
    }//GEN-LAST:event_menuSetProfilActionPerformed

    private void menuSetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSetPassActionPerformed
        // TODO add your handling code here:
        showPanel("pChangePass");
    }//GEN-LAST:event_menuSetPassActionPerformed

    private void menuPengajuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPengajuanActionPerformed
        // TODO add your handling code here:
        showPanel("pPengajuan");
    }//GEN-LAST:event_menuPengajuanActionPerformed

    private void menuGudangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGudangActionPerformed
        // TODO add your handling code here:
        showPanel("pGudang");
    }//GEN-LAST:event_menuGudangActionPerformed

    private void menuPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPermintaanActionPerformed
        // TODO add your handling code here:
        showPanel("pPermintaan");
    }//GEN-LAST:event_menuPermintaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainProgram().setVisible(true);
                /*MainProgram mp = new MainProgram();
                mp.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mp.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbluser;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBar1;
    private javax.swing.JMenu menuBar2;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuGudang;
    private javax.swing.JMenuItem menuLog;
    private javax.swing.JMenuItem menuPegawai;
    private javax.swing.JMenuItem menuPengajuan;
    private javax.swing.JMenuItem menuPenjualan;
    private javax.swing.JMenuItem menuPermintaan;
    private javax.swing.JMenuItem menuSales;
    private javax.swing.JMenuItem menuSetPass;
    private javax.swing.JMenuItem menuSetProfil;
    private javax.swing.JMenuItem menuView;
    // End of variables declaration//GEN-END:variables
}
