/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tubesrpl;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cups
 */
public class PanelViewData extends javax.swing.JPanel {

    private Koneksi conn= new Koneksi();
    private Pegawai pg;
    /**
     * Creates new form PanelViewData
     */
    public PanelViewData(Pegawai pg) {
        initComponents();
        this.pg = pg;
    }

    public void tableModel(String x){
        int i=0,j;
        String query=null;
        String header[];
        if(x.equals("pegawai")){
            j=6;
            header = new String[j];
            header[0] = "ID Pegawai";
            header[1] = "Nama Pegawai";
            header[2] = "Alamat";
            header[3] = "No.Telp";
            header[4] = "Email";
            header[5] = "Tanggal Lahir";
            query = "select * from tb_pegawai";
        }else if(x.equals("barang")){
            j=5;
            header = new String[j];
            header[0] = "ID Barang";
            header[1] = "Nama Barang";
            header[2] = "Warna";
            header[3] = "Harga";
            //header[4] = "Stok";
            query = "select * from tb_barang";
        }else{
            // if(x.equals("penjualan"))
            j=5;
            header = new String[j];
            header[0] = "ID Penjualan";
            header[1] = "ID Barang";
            header[2] = "Nama Penjual";
            header[3] = "Quantity";
            header[4] = "Total Pembayaran";
            query = "select * from tb_penjualan";
        }
        ResultSet rs = null;
        try {
            rs = conn.getData(query);
            while (rs.next()) {
                i++;
            }
            String[][] data = new String[i][j];
            i = 0;
            rs = conn.getData(query);
            while (rs.next()) {
                if(x.equals("pegawai")){
                    data[i][0] = rs.getString("id_pegawai");
                    data[i][1] = rs.getString("nama_pegawai");
                    data[i][2] = rs.getString("alamat");
                    data[i][3] = rs.getString("no_telp");
                    data[i][4] = rs.getString("email");
                    data[i][5] = rs.getString("tgl_lahir");
                }else if(x.equals("barang")){
                    data[i][0] = rs.getString("id_barang");
                    data[i][1] = rs.getString("nama_barang");
                    data[i][2] = rs.getString("warna");
                    data[i][3] = rs.getString("harga");
                    //data[i][4] = rs.getString("stok");
                }else{
                    data[i][0] = rs.getString("id_penjualan");
                    data[i][1] = rs.getString("id_barang");
                    data[i][2] = rs.getString("id_pegawai");
                    data[i][3] = rs.getString("qty");
                    data[i][4] = rs.getString("total");
                }
                i++;
            }
            DefaultTableModel model = new DefaultTableModel(data, header);
            tabel.setModel(model);
        } catch (SQLException ex) {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnviewpgw = new javax.swing.JButton();
        btnviewpjl = new javax.swing.JButton();
        btnviewbrg = new javax.swing.JButton();

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "...", "...", "...", "..."
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("LIHAT DATA");

        btnviewpgw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnviewpgw.setText("View Pegawai");
        btnviewpgw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewpgwActionPerformed(evt);
            }
        });

        btnviewpjl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnviewpjl.setText("View Penjualan");
        btnviewpjl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewpjlActionPerformed(evt);
            }
        });

        btnviewbrg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnviewbrg.setText("View Barang");
        btnviewbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewbrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnviewpgw)
                        .addGap(69, 69, 69)
                        .addComponent(btnviewbrg)
                        .addGap(67, 67, 67)
                        .addComponent(btnviewpjl))
                    .addComponent(jLabel1))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnviewpgw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewpjl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewpgwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewpgwActionPerformed
        // TODO add your handling code here:
        tableModel("pegawai");
    }//GEN-LAST:event_btnviewpgwActionPerformed

    private void btnviewbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewbrgActionPerformed
        // TODO add your handling code here:
        tableModel("barang");
    }//GEN-LAST:event_btnviewbrgActionPerformed

    private void btnviewpjlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewpjlActionPerformed
        // TODO add your handling code here:
        tableModel("penjualan");
    }//GEN-LAST:event_btnviewpjlActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnviewbrg;
    private javax.swing.JButton btnviewpgw;
    private javax.swing.JButton btnviewpjl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
