/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tubesrpl;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cups
 */
public class PanelSales extends javax.swing.JPanel {

    Koneksi conn = new Koneksi();
    /**
     * Creates new form PanelSales
     */
    public PanelSales() {
        initComponents();
        setTabel();
    }

    public void setTabel() {
        int i = 0;
        ResultSet rs,rs2;
        String header[] = {"No.", "ID Pegawai", "Nama Pegawai", "Total penjualan"};
        String query = "select * from tb_pegawai where id_pegawai like'SLS%'";
        
        String tempLokasi;
        try {
            rs = conn.getData(query);
            while (rs.next()) {
                i++;
            }
            String[][] data = new String[i][4];
            i = 0;
            rs = null;
            rs = conn.getData(query);
            while (rs.next()) {
                rs2 = null;
                String query2 = "select SUM(IF(id_pegawai LIKE '"+rs.getString("id_pegawai")+"', qty, 0)) AS jml from tb_penjualan ";
                Koneksi conn2 = new Koneksi();
                rs2 = conn2.getData(query2);
                data[i][0] = i+1+".";
                data[i][1] = rs.getString("id_pegawai");
                data[i][2] = rs.getString("nama_pegawai");
                if(rs2.next()){
                    data[i][3] = rs2.getString("jml");
                }
                i++;
            }
            DefaultTableModel model = new DefaultTableModel(data, header);
            tabel.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : "+e.getMessage(),"Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("DATA PENJUALAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
