/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesrpl;

import java.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cups
 */
public class PanelPegawai extends javax.swing.JPanel {

    Koneksi conn = new Koneksi();
    Pegawai pg;
    ResultSet rs;

    /**
     * Creates new form PanelTambahPegawai
     */
    public PanelPegawai(Pegawai pg) {
        initComponents();
        this.pg = pg;
        reset();
    }

    /* public void menuPegawai(String tipe) {
     clearForm();
     this.setVisible(true);
     if (tipe.equals("input")) {
     jLabel3.setText("DAFTAR PEGAWAI BARU");
     refreshCreateAccount();
     lblpass.setVisible(true);
     txtpass.setVisible(true);
     lblrepass.setVisible(true);
     txtconpass.setVisible(true);
     jLabel5.setVisible(true);
     cbjenisuser.setVisible(true);
     btndelete.setVisible(false);
     btnresetuser.setVisible(false);
     btncreate.setText("CREATE");
     btnedit.setText("CLEAR");
     btncreate.setEnabled(true);
     btnedit.setEnabled(true);
     } else {
     jLabel3.setText("KELOLA DATA PEGAWAI");
     lblpass.setVisible(false);
     txtpass.setVisible(false);
     lblrepass.setVisible(false);
     txtconpass.setVisible(false);
     cbjenisuser.setVisible(false);
     jLabel5.setVisible(false);
     btndelete.setEnabled(true);
     btndelete.setVisible(true);
     btnresetuser.setVisible(true);
     btncreate.setText("SEARCH");
     btnedit.setText("SAVE UPDATE");
     btncreate.setEnabled(false);
     btnedit.setEnabled(false);
     }
     }
     */
    public void refreshCreateAccount() {
        ResultSet rs;
        String query, kode, temp = null;
        int counter = 0;
        if (cbjenisuser.getSelectedItem().toString().equals("Manager")) {
            query = "select * from tb_pegawai where posisi='manager'";
            kode = "MGR";
        } else if (cbjenisuser.getSelectedItem().toString().equals("Sales")) {
            query = "select * from tb_pegawai where posisi='sales'";
            kode = "SLS";
        } else {
            query = "select * from tb_pegawai where posisi='warehouse'";
            kode = "WHK";
        }

        try {
            rs = conn.getData(query);
            while (rs.next()) {
                temp = rs.getString("id_pegawai");
            }
            if (temp != null) {
                counter = Integer.parseInt(temp.substring(4, 8));
                String x = String.format("%04d", ++counter);
                txtidpeg.setText(kode + "-" + x);
            } else {
                txtidpeg.setText(kode + "-0001");
            }
        } catch (SQLException ex) {

        }
    }

    public void reset() {
        txtidpeg.setText(null);
        txtpass.setText(null);
        txtconpass.setText(null);
        txtnama.setText(null);
        txtalamat.setText(null);
        txtnotelp.setText(null);
        txtemail.setText(null);
        cbtgl.setSelectedIndex(0);
        cbbln.setSelectedIndex(0);
        cbthn.setSelectedIndex(0);
        lblpass.setVisible(true);
        txtpass.setVisible(true);
        lblrepass.setVisible(true);
        txtconpass.setVisible(true);
        btncreate.setEnabled(true);
        btnedit.setEnabled(true);
        btndelete.setEnabled(true);
        cbjenisuser.setEnabled(true);
        txtidpeg.setEnabled(true);
        cbjenisuser.setSelectedItem("Pilih Jenis User");
    }

    public Boolean cekIdPegawai(String x) {
        ResultSet rs;
        Boolean temp = false;
        try {
            rs = conn.getData("select * from tb_pegawai where id_pegawai like '" + x + "'");
            if (rs.next()) {
                temp = true;
            }
        } catch (SQLException ex) {

        }
        return temp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cbjenisuser = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtidpeg = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtnotelp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        cbtgl = new javax.swing.JComboBox();
        cbthn = new javax.swing.JComboBox();
        cbbln = new javax.swing.JComboBox();
        lblrepass = new javax.swing.JLabel();
        btncreate = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnresetuser = new javax.swing.JButton();
        txtconpass = new javax.swing.JPasswordField();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("DAFTAR USER BARU");

        cbjenisuser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Sales", "Warehouse Keeper" }));
        cbjenisuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenisuserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Jenis user");

        lblpass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblpass.setText("Password");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("ID Pegawai");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("No. Telp");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Nama");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Alamat");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Email");

        txtidpeg.setEditable(false);

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Tgl. Lahir");

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        cbtgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        cbthn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));

        cbbln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        lblrepass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblrepass.setText("Re-type Password");

        btncreate.setText("Create Account");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnresetuser.setText("RESET");
        btnresetuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpass, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbjenisuser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidpeg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblrepass))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbthn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtconpass, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btncreate))
                        .addGap(18, 18, 18)
                        .addComponent(btnresetuser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbjenisuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidpeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpass)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrepass, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtconpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbthn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnresetuser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(234, 234, 234))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbjenisuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenisuserActionPerformed
        // TODO add your handling code here:
        refreshCreateAccount();
    }//GEN-LAST:event_cbjenisuserActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
        Encryption e = new Encryption();
        if (txtpass.getText().equals(txtconpass.getText())) {
            String tglLahir = cbtgl.getSelectedItem().toString() + " " + cbbln.getSelectedItem().toString() + " " + cbthn.getSelectedItem().toString();
            String query = "insert into tb_pegawai values('" + txtidpeg.getText() + "','" + e.getEncryption(txtpass.getText()) + "','" + cbjenisuser.getSelectedItem().toString() + "','"
                    + txtnama.getText() + "','" + txtalamat.getText() + "','" + txtnotelp.getText() + "','" + txtemail.getText() + "','" + tglLahir + "')";
            conn.runQuery(query);
            reset();
        } else {
            JOptionPane.showMessageDialog(null, "Password konfirmasi tidak sama dengan isi password", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btncreateActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:

        if (btnedit.getText().equals("EDIT")) {
            String input = JOptionPane.showInputDialog(null, "ID Pegawai yang akan diedit :  ", "Edit Data Pegawai", JOptionPane.QUESTION_MESSAGE);
            if (cekIdPegawai(input)) {
                rs = null;
                reset();
                rs = conn.getData("select * from tb_pegawai where id_pegawai like '" + input + "'");
                try {
                    while (rs.next()) {
                        //cbjenisuser.setSelectedItem(rs.getString("posisi"));
                        cbjenisuser.setEnabled(false);
                        txtidpeg.setText(rs.getString("id_pegawai"));
                        txtnama.setText(rs.getString("nama_pegawai"));
                        txtalamat.setText(rs.getString("alamat"));
                        txtnotelp.setText(rs.getString("no_telp"));
                        txtemail.setText(rs.getString("email"));
                        int i = rs.getString("tgl_lahir").length();
                        cbtgl.setSelectedItem((rs.getString("tgl_lahir")).substring(0, 2));
                        cbbln.setSelectedItem((rs.getString("tgl_lahir")).substring(2, (i - 5)));
                        cbthn.setSelectedItem((rs.getString("tgl_lahir")).substring((i - 4), i));
                        btnedit.setText("SAVE UPDATE");
                        btncreate.setEnabled(false);
                        btndelete.setEnabled(false);
                        lblpass.setVisible(false);
                        txtpass.setVisible(false);
                        lblrepass.setVisible(false);
                        txtconpass.setVisible(false);
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error " + e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "ID " + input + " tidak dapat ditemukan", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            String tgl = cbtgl.getSelectedItem().toString() + " " + cbbln.getSelectedItem().toString() + " "
                    + cbthn.getSelectedItem().toString();
            String query = " update tb_pegawai set nama_pegawai='" + txtnama.getText() + "', alamat='" + txtalamat.getText() + "', no_telp='"
                    + txtnotelp.getText() + "', email='" + txtemail.getText() + "', tgl_lahir='" + tgl + "' where id_pegawai='" + txtidpeg.getText() + "'";
            conn.runQuery(query);
            reset();
            JOptionPane.showMessageDialog(null, "Biodata sudah berhasil diperbaharui. Terima kasih.", "Information", JOptionPane.INFORMATION_MESSAGE);
            btnedit.setText("EDIT");
            btncreate.setEnabled(true);
            btndelete.setEnabled(true);
            reset();
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try {
            String input = JOptionPane.showInputDialog(null, "ID Pegawai yang akan dihapus :  ", "Hapus Data Pegawai", JOptionPane.QUESTION_MESSAGE);

            if (cekIdPegawai(input)) {
                int in = JOptionPane.showConfirmDialog(null, "Data pegawai atas ID " + input + " akan dihapus. Lanjutkan menghapus data ?", "Pesan Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
                if (in == 0) {
                    String query = "delete from tb_pegawai where id_pegawai='" + input + "'";
                    conn.runQuery(query);
                    reset();
                    JOptionPane.showMessageDialog(null, "Data pegawai atas ID " + txtidpeg.getText() + " berhasil dihapus", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Data pegawai atas ID " + input + " tidak dapat ditemukan", "Warning", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnresetuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetuserActionPerformed
        // TODO add your handling code here:
        reset();
        txtidpeg.setText(null);
        txtidpeg.setEnabled(true);
    }//GEN-LAST:event_btnresetuserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnresetuser;
    private javax.swing.JComboBox cbbln;
    private javax.swing.JComboBox cbjenisuser;
    private javax.swing.JComboBox cbtgl;
    private javax.swing.JComboBox cbthn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblrepass;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JPasswordField txtconpass;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtidpeg;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
