/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tubesrpl;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cups
 */
public class PanelGudang extends javax.swing.JPanel {

    private Koneksi conn = new Koneksi();
    private ResultSet rs;
    /**
     * Creates new form PanelLokasi
     */
    public PanelGudang() {
        initComponents();
    }

    public void reset(){
        txtidgudang.setText(null);
        cbidwk.setSelectedIndex(0);
        txtlokasi.setText(null);
    }
    
    public Boolean cekIdBarang(String x) {
        ResultSet rs;
        Boolean temp = false;
        try {
            rs = conn.getData("select * from tb_gudang where id_gudang like '" + x + "'");
            if (rs.next()) {
                temp = true;
            }
        } catch (SQLException ex) {

        }
        return temp;
    }
    
    public void setIsi(){
        try {
            rs=null;
            rs = conn.getData("select * from tb_pegawai where id_pegawai like'WHK%'");
            while(rs.next()){
                cbidwk.addItem(rs.getString("id_pegawai"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelGudang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidgudang = new javax.swing.JTextField();
        btncreate = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnresetuser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtlokasi = new javax.swing.JTextArea();
        cbidwk = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ID Gudang");
        add(jLabel1);
        jLabel1.setBounds(10, 69, 95, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Lokasi");
        add(jLabel2);
        jLabel2.setBounds(10, 138, 96, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("ID Kepala Gudang");
        add(jLabel3);
        jLabel3.setBounds(10, 102, 95, 15);
        add(txtidgudang);
        txtidgudang.setBounds(138, 71, 124, 20);

        btncreate.setText("CREATE");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        add(btncreate);
        btncreate.setBounds(60, 250, 112, 32);

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        add(btnedit);
        btnedit.setBounds(210, 250, 112, 32);

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        add(btndelete);
        btndelete.setBounds(60, 300, 112, 32);

        btnresetuser.setText("RESET");
        btnresetuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetuserActionPerformed(evt);
            }
        });
        add(btnresetuser);
        btnresetuser.setBounds(210, 300, 112, 32);

        txtlokasi.setColumns(20);
        txtlokasi.setRows(5);
        jScrollPane1.setViewportView(txtlokasi);

        add(jScrollPane1);
        jScrollPane1.setBounds(138, 138, 260, 96);

        cbidwk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Id Warehouse Keeper" }));
        add(cbidwk);
        cbidwk.setBounds(140, 100, 160, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("KELOLA GUDANG");
        add(jLabel6);
        jLabel6.setBounds(10, 10, 200, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
        try{
            if (txtidgudang.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Data barang tidak berhasil diinputkan, isi semua form", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                String query = "insert into tb_gudang values('" + txtidgudang.getText() + "','" + cbidwk.getSelectedItem().toString() + "','"
                + txtlokasi.getText() + "')";
                conn.runQuery(query);
                JOptionPane.showMessageDialog(null, "Data barang berhasil diinputkan", "Information", JOptionPane.INFORMATION_MESSAGE);
                reset();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btncreateActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:

        if (btnedit.getText().equals("EDIT")) {
            String input = JOptionPane.showInputDialog(null, "ID Barang yang akan diedit :  ", "Edit Data Barang", JOptionPane.QUESTION_MESSAGE);
            if (cekIdBarang(input)) {
                rs = null;
                reset();
                rs = conn.getData("select * from tb_barang where id_barang like '" + input + "'");
                try {
                    while (rs.next()) {
                        txtidgudang.setText(rs.getString("id_gudang"));
                        txtidgudang.setEnabled(false);
                        cbidwk.setSelectedItem(rs.getString("id_pegawai"));
                        txtlokasi.setText(rs.getString("lokasi"));
                        btnedit.setText("SAVE UPDATE");
                        btncreate.setEnabled(false);
                        btndelete.setEnabled(false);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error " + e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "ID barang : " + input + " tidak dapat ditemukan", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            String query = "update tb_gudang set id_pegawai='" + cbidwk.getSelectedItem().toString() + "', lokasi='" + txtlokasi.getText()
            +"' where id_gudang='" + txtidgudang.getText() + "'";
            conn.runQuery(query);
            reset();
            JOptionPane.showMessageDialog(null, "Data gudang sudah berhasil diperbaharui. Terima kasih.", "Information", JOptionPane.INFORMATION_MESSAGE);
            btnedit.setText("EDIT");
            btncreate.setEnabled(true);
            btndelete.setEnabled(true);
            reset();
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try {
            String input = JOptionPane.showInputDialog(null, "ID gudang yang akan dihapus :  ", "Hapus Data Barang", JOptionPane.QUESTION_MESSAGE);

            if (cekIdBarang(input)) {
                int in = JOptionPane.showConfirmDialog(null, "Data gudang dengan ID " + input + " akan dihapus. Lanjutkan menghapus data ?", "Pesan Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
                if (in == 0) {
                    String query = "delete from tb_gudang where id_gudang='" + input + "'";
                    conn.runQuery(query);
                    reset();
                    JOptionPane.showMessageDialog(null, "Data barang dengan ID " + txtidgudang.getText() + " berhasil dihapus", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Data barang dengan ID " + input + " tidak dapat ditemukan", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnresetuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetuserActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnresetuserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnresetuser;
    private javax.swing.JComboBox cbidwk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtidgudang;
    private javax.swing.JTextArea txtlokasi;
    // End of variables declaration//GEN-END:variables
}
