/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesrpl;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cups
 */
public class PanelPermintaan extends javax.swing.JPanel {

    private Pegawai pg;
    private Koneksi conn = new Koneksi();
    ResultSet rs;

    /**
     * Creates new form PanelPersediaan
     */
    public PanelPermintaan(Pegawai pg) {
        initComponents();
        this.pg = pg;
        setTabel();
    }

    public void setTabel() {
        int i = 0;
        ResultSet tempRs;
        String header[] = {"ID", "ID Barang", "Id Gudang", "Qty", "ID Pengaju"};

        try {
            String query = "select * from tb_pengajuan where id_manager like'" + pg.getIdPegawai() + "'";
            rs = conn.getData(query);
            while (rs.next()) {
                i++;
            }
            String[][] data = new String[i][5];
            i = 0;
            rs = null;
            rs = conn.getData(query);
            while (rs.next()) {
                data[i][0] = rs.getString("id_pengajuan");
                data[i][1] = rs.getString("id_barang");
                data[i][2] = rs.getString("id_gudang");
                data[i][3] = rs.getString("qty");
                data[i][4] = rs.getString("id_pengaju");
                i++;
            }
            DefaultTableModel model = new DefaultTableModel(data, header);
            tabel.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : "+e.getMessage(), "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnapprove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        btnapprove.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnapprove.setText("APPROVE");
        btnapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapproveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("DAFTAR PERMINTAAN BARANG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(btnapprove, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnapprove, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapproveActionPerformed
        // TODO add your handling code here:

        int row = tabel.getSelectedRow();
        Object input1 = tabel.getValueAt(row, 1);
        Object input2 = tabel.getValueAt(row, 2);
        Object input3 = tabel.getValueAt(row, 3);
        Object input4 = tabel.getValueAt(row, 0);

        ResultSet rs;
        rs = conn.getData("select * from tb_persediaan where id_barang like'"+input1.toString()+"' and id_gudang like'"+input2.toString()+"'");
        try {
            if(rs.next()){
                conn.runQuery("update tb_persediaan set stok="+(Integer.parseInt(rs.getString("stok"))+Integer.parseInt(input3.toString()))+
                        " where id_barang ='"+input1.toString()+"' and id_gudang ='"+input2.toString()+"'");
            }else{
                String query = " insert into tb_persediaan(id_barang, id_gudang, stok) values('" + input1.toString() + "','" + input2.toString()
                + "','" + input3.toString() + "')";
                conn.runQuery(query);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelPermintaan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Penambahan barang berhasil", "Information", JOptionPane.INFORMATION_MESSAGE);
        String query = "delete from tb_pengajuan where id_pengajuan='" + input4.toString() + "'";
        conn.runQuery(query);
        setTabel();
    }//GEN-LAST:event_btnapproveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapprove;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
